version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: build/
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: build/
    schedule:
      interval: weekly
