name: Cleanup GHCR Images

on:
  workflow_dispatch:        # Allows manual triggering
  schedule:
    - cron: '30 2 * * MON'  # Runs every Monday at 02:30 UTC

permissions:
  contents: read
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old container versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: fedora-toolbox              # Replace with your GHCR package name
          package-type: container
          min-versions-to-keep: 30                  # Adjust to keep the last N images
          delete-only-untagged-versions: "false"    # Set to 'true' to only delete untagged images
