name: container

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

permissions:
  packages: write

jobs:
  build-test-push:
    env:
      PACKAGES_REGISTRY: ghcr.io/ljbcloud
    strategy:
      matrix:
        FEDORA_VERSION: [42]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Generate Image Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/ljbcloud/fedora-toolbox
          tags: |
            type=sha,format=short,prefix=
            type=ref,event=tag
            type=ref,event=branch
            type=raw,enable=${{ startsWith(github.ref, 'refs/heads/main') }},value=${{ matrix.FEDORA_VERSION }}

      - name: Login to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Build Image
        uses: redhat-actions/buildah-build@v2
        id: build
        with:
          context: ${{ env.GITHUB_WORKSPACE }}/build
          build-args: |
            FEDORA_VERSION=${{ matrix.FEDORA_VERSION }}
            PACKAGES_REGISTRY=${{ env.PACKAGES_REGISTRY }}
          containerfiles: |
            ${{ env.GITHUB_WORKSPACE }}/build/Containerfile
          platforms: |
            linux/amd64
          labels: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}

      - name: Push Image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
